WebQuiz-master/WebQuiz/Models/UserDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebQuiz.Models
{
    public class UserDetails
    {
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }


    }
}

WebQuiz-master/WebQuiz/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebQuiz.Models;


namespace WebQuiz.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

WebQuiz-master/WebQuiz/Controllers/PartialController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebQuiz.Models;
using System.Linq;

namespace WebQuiz.Controllers
{
    public class PartialController : Controller
    {
        List<UserDetails> details = new List<UserDetails>()
            {
               new UserDetails { Name="Divya",Lastname="Ramapriya",Email="DivyaRamapriya16@gmail.com",PhoneNumber="045678901" },
               new UserDetails { Name="Matt",Lastname="M",Email="Matt@gmail.com",PhoneNumber="0459078901" },
               new UserDetails { Name="Vikram",Lastname="S",Email="Vikram@gmail.com",PhoneNumber="045677901" },
               new UserDetails { Name="Josh",Lastname="Raymer",Email="Josh@gmail.com",PhoneNumber="045678901" },
               new UserDetails { Name="Naveen",Lastname="Y",Email="Naveen@gmail.com",PhoneNumber="04564401" },
               new UserDetails { Name="Thomas",Lastname="T",Email="Thomas@gmail.com",PhoneNumber="046578901" },
               new UserDetails { Name="Phebe",Lastname="M",Email="Phebe@gmail.com",PhoneNumber="045689901" },
               new UserDetails { Name="Monica",Lastname="J",Email="Monica@gmail.com",PhoneNumber="045668901" }
            };
        public string Name { get; set; }

        // GET: Partial
        public ActionResult Main()
        {
            return View();
        }

        // GET: Partial
        public ActionResult Default()
        {
            return View();
        }

        // GET: Partial
        public ActionResult Profile()
        {
            return View();
        }

        public ActionResult User(string txtValue, string sortOrder)
        {
         if (!String.IsNullOrEmpty(sortOrder))
            {
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                ViewBag.LastNameSortParm = String.IsNullOrEmpty(sortOrder) ? "lastname_desc" : "";
                ViewBag.EmailSortParm = String.IsNullOrEmpty(sortOrder) ? "email_desc" : "";
                var sort = from m in details
                               select m;
                switch (sortOrder)
                {
                    case "name_desc":
                        sort = sort.OrderByDescending(s => s.Name);
                        break;
                    case "lastname_desc":
                        sort = sort.OrderByDescending(s => s.Lastname);
                        break;
                    case "email_desc":
                        sort = sort.OrderByDescending(s => s.Email);
                        break;
                    default:
                        sort = sort.OrderBy(s => s.Lastname);
                        break;
                }
                return View(sort);
            }
         else if (!String.IsNullOrEmpty(txtValue))
            {
                var Select = from m in details
                         select m;


                Select = Select.Where(s => s.Name.ToLower().Contains(txtValue.ToLower()));
                return View(Select);
            }
            else
            return View(details);
        }

      
    }
}

WebQuiz-master/WebQuiz/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" media="screen" href="~/css/webquiz.css">
    <link rel="stylesheet" type="text/css" media="screen" href="~/Content/Site.css">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <!-- JQuery core -->
    <script src="~/js/jquery.js"></script>
    <!-- Angular2 core -->
    <script src="~/js/angular.js"></script>
    <!-- Angular2 config-->
    <script src="~/systemjs.config.js"></script>
    <script>

        System.import('app').catch(function (err) { console.error(err); });
    </script>
</head>
<body>
    <my-app>
        Loading...
    </my-app>
</body>
</html>

WebQuiz-master/WebQuiz/Views/Partial/Default.cshtml
@{
    Layout = null;
}

<h3>Demo Component - Calling demo service</h3>

<div>
    <div class="alert alert-success" role="alert"><strong>Server Time</strong> {{serverTime | date:'medium'}}</div>    
    <br />
    <button class="btn btn-default" type="submit" (click)="getTimeFromServer()">Time From Server</button>
</div>

WebQuiz-master/WebQuiz/Views/Partial/Main.cshtml
@{
    Layout = null;
}
<div class="container">
    <ul class="nav nav-pills">
        <li role="presentation" [class.active]="isActive('')"><a routerLink="">Home</a></li>
        <li role="presentation" [class.active]="isActive('/profile')"><a routerLink="/profile">Profile</a></li>
        <li role="presentation" [class.active]="isActive('/user')"><a routerLink="/user">User</a></li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <router-outlet></router-outlet>
        </div>            
    </div>    
</div>

WebQuiz-master/WebQuiz/Views/Partial/Profile.cshtml
@{
    Layout = null;
}

<h3>Profile Component</h3>
<div class="panel panel-default">
    <div class="panel-heading">Profile</div>
    <div class="panel-body">
        <div class="form-group">
            <label for="txtName">Name:</label>
            <span id="txtName">{{profile?.Name}}</span>            
        </div>
        <div class="form-group">
            <label for="txtLastName">Last Name:</label>
            <span id="txtLastName">{{profile?.LastName}}</span>
        </div>
        <div class="form-group">
            <label for="txtDOB">Date of Birth:</label>
            <span id="txtDOB">{{profile?.DateOfBirth | date}}</span>
        </div>
    </div>
</div>

WebQuiz-master/WebQuiz/Views/Partial/user.cshtml
@model IEnumerable<WebQuiz.Models.UserDetails>
@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("User", "Partial", FormMethod.Get, new { onkeydown = "return event.keyCode" }))
{
    <p>
        @Html.Label("Click to Back to Home Page")
        <br />
        @Html.ActionLink("Back", "Index", "Home")
        <br/>
         @Html.Label("Click SearchView Link to Search By Name")
        <br/>
        @Html.ActionLink("SearchView", "User", "Partial")         
        <br/>
        <br/>
         @Html.TextBox("txtValue", "", new { placeholder = "Please press Enter Key" })
        <br />
        <input type="submit" id="submit" value="submit" hidden="hidden" />
    </p>
   

}
<html>
<head>
          <link rel="stylesheet" type="text/css" media="screen" href="~/Content/Site.css">
</head>
<body>
    <div class="panel panel-default">
        <div class="divTable" style="width: 50%;border: 5px solid #000;">
            <div class="divTableBody">
                <div class="Heading">
                    <div class="Cell">
                        @Html.ActionLink("Name", "User", new { txtValue ="", sortOrder = "name_desc" })
                    </div>
                    <div class="Cell">
                        @Html.ActionLink("Last Name", "User", new { txtValue = "", sortOrder = "lastname_desc" })
                    </div>
                    <div class="Cell">
                        @Html.ActionLink("EmailID", "User", new { txtValue = "",  sortOrder = "email_desc" })
                    </div>
                    <div class="Cell">
                        <a href="#">Phone Number</a>
                    </div>
                </div>
                @foreach (var i in Model)
            {
                    <div class="Row">
                        <div class="Cell">
                            <p>@i.Name</p>
                        </div>
                        <div class="Cell">
                            <p>@i.Lastname</p>
                        </div>
                        <div class="Cell">
                            <p>@i.Email</p>
                        </div>
                        <div class="Cell">
                            <p>@i.PhoneNumber</p>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    
</body>
</html>

WebQuiz-master/WebQuiz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" media="screen" href="~/css/webquiz.css">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <!-- JQuery core -->
    <script src="~/js/jquery.js"></script>
    <!-- Angular2 core -->
    <script src="~/js/angular.js"></script>
    <!-- Angular2 config-->
    <script src="~/systemjs.config.js"></script>
    <script>

        System.import('app').catch(function (err) { console.error(err); });
    </script>
</head>
<body>
    <my-app>
        Loading...
    </my-app>
    @RenderSection("scripts", required: false)
</body>
</html>